### ISSUE TITLE
Failed to generate map

### ISSUE THREAD

**Issue by ThomasDier** [ropensci/mapscanner#12]
I am probably to inexperienced, but i couldn't generate a map.
I tried the following ways and always got the same error
"Fehler in curl::curl_download(url = api_query, outfile) : HTTP error 401"

test <- ms_generate_map("Gallus", style = "streets", mapname = "gallus")
Fehler in curl::curl_download(url = api_query, outfile) : HTTP error 401.

library(osmdata)
getbb("Gallus")
        min      max
x -1.164082 -1.02943
y 42.758790 42.83095
test <- getbb("Gallus")
test2 <- ms_generate_map(test, style = "streets", mapname = "gallus")
Fehler in curl::curl_download(url = api_query, outfile) : HTTP error 401.

Manually selected the area for the map via:
https://www.openstreetmap.org/export#map=16/50.1044/8.6319
<img width="1369" alt="osm export" src="https://user-images.githubusercontent.com/42271539/63280542-49828f00-c2ab-11e9-99f5-f49905310692.png">
test <- ms_generate_map(c(8.6210, 50.1014, 8.6417, 50.1086), style = "streets", mapname = "gallus")
Fehler in curl::curl_download(url = api_query, outfile) : HTTP error 401.

**Comment by mpadge** [comment]
Hi @ThomasDier, thanks a lot for your interest in the package, and apologies for not having been able to reply until now. Your problems should now be solved by #13, and associated updates to the package documentation, both the [`README`](https://github.com/mpadge/mapscanner) and the [vignette](https://mpadge.github.io/mapscanner/articles/mapscanner.html). You need to obtain and set a personal key from [mapbox](https://docs.mapbox.com/api/#access-tokens-and-token-scopes) in order to access the map tiles used to generate the maps. Sorry that I had previously neglected to clarify that. Hope it all works for you now, and please feel free to ask any and all further questions.
