### ISSUE TITLE
error converting to spatial format

### ISSUE THREAD

**Issue by khondula** [ropensci/mapscanner#17]
re:  https://github.com/ropensci/software-review/issues/330#issuecomment-528962487

**Comment by mpadge** [comment]
Thanks @khondula. This seems to be due to lines being drawn or scanned in very thin, so that the raster representations actually become disconnected. The (default) underlying routines currently presume all features are entirely contiguous in the raster representation, and so fail on these. Of course, for the package to be usable, they should not fail at all, so I need to fix this. I'm working of ways of stitching fragmented pieces back together ...

**Comment by mpadge** [comment]
@khondula Thank you so much for all of you data you emailed to me as part of the [rOpenSci review process](https://github.com/ropensci/software-review/issues/330#event-2513283441). All of them were complete breaking cases, and have helped enormously to make the package much more robust. Lots of the internal mechanisms have been completely reconceived. The package now makes an initial guess at number of items to be extracted, then estimates a signal-to-noise threshold to optimally identify those features. There is also an additional optional parameter `nitems` which, if specified, overrides the automatic estimation. The following table summarises what now happens:


file                            | result?
------------------------------- | -------
choptank-annotated.pdf          | ok
choptank-annotated.png          | ok
choptank-annotate2.png          | ok
choptank-annotate3.pdf          | ok
choptank-annotate4.pdf          | ok
choptank-annotate-5.pdf         | auto-detects only 5 items and kinda fails on one, but works perfectly with `nitems = 6`
choptank-annotate-line.png      | works perfectly as polygon (but actual line-detection not yet implemented; see #5)
choptank-annotate-points.png    | works perfectly as points, hulls, and polygons
omaha-pink2.pdf                 | auto-detects only 1 item but then errors appropriately; specifying `nitems = 2` works
omaha-pink.pdf                  | works, but inaccurately because fails to trim border

(I'll make a copy of this in the review issue)

Enormously indebted!!

**Comment by khondula** [comment]
closing as per [review comment](https://github.com/ropensci/software-review/issues/330#issuecomment-540320930) confirming it works!
