### ISSUE TITLE
Question: Usage with Google Maps

### ISSUE THREAD

**Issue by SantoshSrinivas79** [ropensci/mapscanner#36]
The package looks great ... is there a way to do use this with Google Maps instead on Mapbox?

Many thanks!

**Comment by mpadge** [comment]
Thanks for the interest @SantoshSrinivas79. Before i answer your question, let me state that i see no reason why alternative tile providers ought to make any difference? The package is intended simply to generate underlying maps which are able to clearly drawn upon. This requires mapbox, because they are the only service providing appropriately stylized tiled for such usage. I would nevertheless be interested to hear if there was a specific reason why the mapbox service might not be appropriate for a particular use case. In the meantime, the direct answer to your question:

### is there a way to use this with Google Maps?

No chance: google's terms are absolutely unacceptable, and make it impossible to use any google produces in software like this. Their [terms of use for maps](https://maps.google.com/help/terms_maps/) very clearly state:

1. When using Google Maps/Google Earth, you may not (or allow those acting on your behalf to):
    a. redistribute or sell any part of Google Maps/Google Earth or create a new product or service based on Google Maps/Google Earth (unless you use the Google Maps/Google Earth APIs in accordance with their terms of service);
    ...
    c. mass download or create bulk feeds of the content (or let anyone else do so);
    d. use Google Maps/Google Earth to create or augment any other mapping-related dataset (including a mapping or navigation dataset, business listings database, mailing list, or telemarketing list) for use in a service that is a substitute for, or a substantially similar service to, Google Maps/Google Earth;

This package:

- requires bulk downloading, contravening (1c),
- is intended to facilitate redistribution of maps, contravening (1a), and
- is intended to allow people to augment maps, contravening (1d).

But mostly: google reserves the right at any stage to take any idea which uses any google product (like maps, in this case), develop a similar product, and then claim infringement of their own conditions. No chance.
